---
# Enable/Disable varius tasks
configure_ssh_keys: true
github_ssh_keys_username: ckr
configure_zplug: true
configure_extra_packages: true
configure_tmux: true

# Homebrew configuration
# Enable/Disable this role
homebrew_enable: true
homebrew_packages_installed:
  - asciinema
  - coreutils
  - fabric
  - gd
  - gpg
  - htop-osx
  - kubernetes-cli
  - mas
  - pwgen
  - pyenv
  - python
  - rlwrap
  - socat
  - sslscan
  - tmux
  - tree
  - watch
  - yarn
  - npm
  - bat
  - awscli
  - nvim
  - fzf
  - ripgrep
  - stow
  - zplug
  - lazygit
  - ansible-lint
  - yamllint
  - hugo
  - certbot
  - git-delta
  - tokei
  - duf
  - eza
  - oh-my-posh
homebrew_casks_installed:
  - 1password-cli
  - burp-suite
  - gpg-suite
  - istat-menus
  - iterm2
  - rectangle
  - spotify
  - sublime-text
  - visual-studio-code
  - shottr
  - whatsapp
  - discord
  - transmit
  - git-credential-manager
# Composer configuration
composer_enable: true
composer_packages:
  - name: phing/phing
  - name: squizlabs/php_codesniffer
  - name: phpmd/phpmd
  - name: friendsofphp/php-cs-fixer
  - name: phploc/phploc
  - name: wapmorgan/php-deprecation-detector
  - name: sebastian/phpcpd
  - name: phpunit/php-code-coverage
  - name: phpunit/phpunit
  - name: phpstan/phpstan
  - name: povils/phpmnd

# MacTweaks configuration
mactweaks_enable: true
mactweaks_system_enable: true
mactweaks_system_defaults:
  - { domain: com.apple.dock, key: autohide-time-modifier, type: int, value: 0 }
  - { domain: com.apple.dock, key: autohide, type: int, value: 0 }
  - { domain: com.apple.dock, key: orientation, type: string, value: left }
  - { domain: com.apple.dock, key: show-recents, type: int, value: 0 }
  - { domain: com.apple.dock, key: tilesize, type: int, value: 50 }
  - { domain: com.apple.dock, key: largesize, type: float, value: 58 }
  - { domain: com.apple.screensaver, key: askForPassword, type: int, value: 1 }
  - { domain: com.apple.screensaver, key: tokenRemovalAction, type: int, value: 0 }
  - { domain: com.apple.screensaver, key: askForPasswordDelay, type: float, value: !!float "0.0" }
  # TODO: Fix this ansible is having an issue setting them.
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate.plist, key: AutomaticCheckEnabled, type: int, value: 1 }
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate.plist, key: ConfigDataInstall, type: bool, value: true }
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate.plist, key: CriticalUpdateInstall, type: bool, value: true }
mactweaks_dock_enable: true
mactweaks_dock_items_remove:
  - Safari
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - News
  - Keynote
  - Numbers
  - Pages
  - App Store
mactweaks_dock_items_persist:
  - name: Launchpad
    path: /System/Applications/Launchpad.app/
    section: apps
    pos: 1
  - name: Shift
    path: /Applications/Shift.app/
    section: apps
    pos: 2
  - name: Google Chrome
    path: /Applications/Google Chrome.app/
    section: apps
    pos: 3
  - name: System Settings
    path: /System/Applications/System Settings.app/
    section: apps
    pos: 4
  - name: Messages
    path: /System/Applications/Messages.app/
    section: apps
    pos: 5
  - name: WhatsApp
    path: /Applications/WhatsApp.app/
    section: apps
    pos: 6
  - name: Messenger
    path: /Applications/Messenger.app/
    section: apps
    pos: 7
  - name: Joplin
    path: /Applications/Joplin.app/
    section: apps
    pos: 8
  - name: Pocket
    path: /Applications/Pocket.app/
    section: apps
    pos: 9
  - name: Home
    path: /System/Applications/Home.app/
    section: apps
    pos: 10
  - name: iTerm
    path: /Applications/iTerm.app/
    section: apps
    pos: 11
  - name: Dropbox
    path: /Users/ckr/Dropbox/
    section: others
    pos: 1
  - name: Downloads
    path: /Users/ckr/Downloads/
    section: others
    pos: 2

# MAS configuration
mas_enable: true
mas_signin_dialog: true
# Update all
mas_upgrade_all: false
# Make sure the following apps are installed/uninstalled
# Installed List
mas_installed:
  - { id: 866773894, name: Quiver }
  - { id: 409907375, name: Remote Desktop }
  - { id: 1480068668, name: Messenger }
  - { id: 1516894961, name: Codye }
  - { id: 1303222628, name: Paprika Recipe Manager 3 }
  - { id: 587769990, name: EyeFriendly }
  - { id: 638161122, name: YubiKey Personalization Tool }
  - { id: 425424353, name: The Unarchiver }
  - { id: 924726344, name: Deliveries }
  - { id: 568494494, name: Pocket }
  - { id: 1510445899, name: "Meeter for Zoom, Teams & Co" }

# Node packages via yarn
yarn_packages: []
# Node packages via npm
npm_packages: []
# Python packages via pip
pip_packages: []
# Ruby gems
gem_packages: []
