---
# Enable/Disable varius tasks
configure_ssh_keys: true
github_ssh_keys_username: ckr
configure_zplug: true
configure_extra_packages: true
configure_tmux: true

# Homebrew configuration
homebrew_enable: true
homebrew_packages_installed:
  - ack
  - asciinema
  - awscli
  - blueutil
  - coreutils
  - cowsay
  - fabric
  - figlet
  - gd
  - gnupg
  - goaccess
  - gpgme
  - htop
  - imagemagick
  - kubernetes-cli
  - libiconv
  - libyaml
  - lolcat
  - mas
  - mysql-client
  - nmap
  - node
  - p7zip
  - percona-toolkit
  - libpsl
  - pssh
  - pv
  - pwgen
  - pyenv
  - python
  - python3
  - rbenv
  - rbenv-default-gems
  - rlwrap
  - ruby
  - screenfetch
  - selecta
  - socat
  - sphinx-doc
  - sqlmap
  - sslscan
  - terraform
  - tmux
  - tree
  - vault
  - watch
  - wget
  - zlib
  - yarn
  - npm
  - bat
  - ripgrep
  - neovim
  - git-lfs
  - openssl@1.1
  - openssl@3
  - snyk
  - stow
  - bfg
  - grc
homebrew_casks_installed:
  - 1password-cli
  - alfred
  - amethyst
  - apparency
  - bartender
  - docker
  - duo-connect
  - gpg-suite
  - istat-menus
  - iterm2
  - postman
  - rectangle
  - spotify
  - sublime-text
  - visual-studio-code
  - jetbrains-toolbox

# Composer configuration
composer_enable: true
composer_packages:
  - name: phing/phing
  - name: squizlabs/php_codesniffer
  - name: phpmd/phpmd
  - name: friendsofphp/php-cs-fixer
  - name: phploc/phploc
  - name: wapmorgan/php-deprecation-detector
  - name: sebastian/phpcpd
  - name: phpunit/php-code-coverage
  - name: phpunit/phpunit
  - name: phpmetrics/phpmetrics
  - name: phpstan/phpstan
  - name: povils/phpmnd

# MacTweaks configuration
mactweaks_enable: true
mactweaks_system_enable: true
mactweaks_system_defaults:
  - { domain: com.apple.dock, key: autohide-time-modifier, type: int, value: 0 }
  - { domain: com.apple.dock, key: autohide, type: int, value: 1 }
  - { domain: com.apple.dock, key: orientation, type: string, value: left }
  - { domain: com.apple.dock, key: show-recents, type: int, value: 0 }
  - { domain: com.apple.dock, key: tilesize, type: int, value: 50 }
  - { domain: com.apple.dock, key: largesize, type: float, value: 58 }
  - { domain: com.apple.screensaver, key: askForPassword, type: int, value: 1 }
  - { domain: com.apple.screensaver, key: tokenRemovalAction, type: int, value: 0 }
  - { domain: com.apple.screensaver, key: askForPasswordDelay, type: float, value: 0.0 }
  # TODO: Fix this ansible is having an issue setting them.
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate, key: AutomaticCheckEnabled, type: int, value: 1 }
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate, key: ConfigDataInstall, type: bool, value: true }
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate, key: CriticalUpdateInstall, type: bool, value: true }

# MAS configuration
mas_enable: true
mas_signin_dialog: true
# Update all
mas_upgrade_all: false
# Make sure the following apps are installed/uninstalled
# Installed List
mas_installed:
  - id: 1516894961
    name: "Codye"
  - id: 866773894
    name: "Quiver"
  - id: 1491071483
    name: "Tot"
  - id: 904280696
    name: "Things"
  - id: 1516894961
    name: "Codye"
  - id: 587769990
    name: "EyeFriendly"
  - id: 638161122
    name: "YubiKey Personalization Tool"
  - id: 426410278
    name: "Flexiglass"
  - id: 425424353
    name: "The Unarchiver"
  - id: 568494494
    name: "Pocket"
  - id: 1510445899
    name: "Meeter"
  - id: 1354318707
    name: "Core Tunnel"
  - id: 904280696
    name: "Things"

# Node packages via yarn
yarn_packages: []

# Node packages via npm
npm_packages: []

# Python packages via pip
pip_packages: []

# Ruby gems
gem_packages: []
