---
# Enable/Disable varius tasks
configure_ssh_keys: true
github_ssh_keys_username: ckr
configure_zplug: true
configure_extra_packages: true

# Homebrew configuration
homebrew_enable: true
homebrew_packages_installed:
  - ack
  - asciinema
  - awscli
  - blueutil
  - coreutils
  - couchdb
  - cowsay
  - csshx
  - dfu-programmer
  - dfu-util
  - fabric
  - figlet
  - gd
  - gnupg
  - goaccess
  - gpg
  - gpgme
  - hashcat
  - htop
  - htop-osx
  - hydra
  - imagemagick
  - iperf3
  - kubernetes-cli
  - libiconv
  - libyaml
  - links
  - lolcat
  - mas
  - mysql
  - mysql-client
  - nikto
  - nmap
  - node
  - p7zip
  - percona-toolkit
  - php@7.2
  - php@7.3
  - php@7.4
  - postgresql
  - pssh
  - pv
  - pwgen
  - pyenv
  - python
  - python2
  - python3
  - rbenv
  - rbenv-default-gems
  - redis
  - rlwrap
  - ruby
  - screenfetch
  - selecta
  - socat
  - sphinx-doc
  - sqlmap
  - sslscan
  - terraform
  - tmux
  - tor
  - tree
  - vault
  - watch
  - wget
  - zlib
  - yarn
  - npm
homebrew_casks_installed:
  - 1password
  - alfred
  - amethyst
  - bartender
  - burp-suite
  - cakebrew
  - docker
  - dropbox
  - duo-connect
  - flexiglass
  - google-chrome
  - gpg-suite
  - istat-menus
  - iterm2
  - lens
  - neo4j
  - postman
  - rectangle
  - sequel-pro
  - shift
  - slack
  - spotify
  - sublime-text
  - visual-studio-code
  - zerotier-one

# Composer configuration
composer_enable: true
composer_packages:
  - name: phing/phing
  - name: squizlabs/php_codesniffer
  - name: phpmd/phpmd
  - name: friendsofphp/php-cs-fixer
  - name: phploc/phploc
  - name: wapmorgan/php-deprecation-detector
  - name: sebastian/phpcpd
  - name: phpunit/php-code-coverage
  - name: phpunit/phpunit
  - name: phpmetrics/phpmetrics
  - name: phpstan/phpstan
  - name: povils/phpmnd

# MacTweaks configuration
mactweaks_enable: true
mactweaks_system_enable: true
mactweaks_system_defaults:
  - { domain: com.apple.dock, key: autohide-time-modifier, type: int, value: 0 }
  - { domain: com.apple.dock, key: autohide, type: int, value: 0 }
  - { domain: com.apple.dock, key: orientation, type: string, value: left }
  - { domain: com.apple.dock, key: show-recents, type: int, value: 0 }
  - { domain: com.apple.dock, key: tilesize, type: int, value: 50 }
  - { domain: com.apple.dock, key: largesize, type: float, value: 58 }
  - { domain: com.apple.screensaver, key: askForPassword, type: int, value: 1 }
  - { domain: com.apple.screensaver, key: tokenRemovalAction, type: int, value: 0 }
  - { domain: com.apple.screensaver, key: askForPasswordDelay, type: float, value: 0.0 }
  # TODO: Fix this ansible is having an issue setting them.
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate, key: AutomaticCheckEnabled, type: int, value: 1 }
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate, key: ConfigDataInstall, type: bool, value: true }
  # - { domain: /Library/Preferences/com.apple.SoftwareUpdate, key: CriticalUpdateInstall, type: bool, value: true }
mactweaks_dock_enable: true
mactweaks_dock_items_remove:
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - News
  - 'App Store'
mactweaks_dock_items_persist:
  - name: "Launchpad"
    path: "/System/Applications/Launchpad.app/"
    section: "apps"
    pos: 1
  - name: "Shift"
    path: "/Applications/Shift.app/"
    section: "apps"
    pos: 2
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    section: "apps"
    pos: 3
  - name: "Postman"
    path: "/Applications/Postman.app/"
    section: "apps"
    pos: 4
  - name: "Calendar"
    path: "/System/Applications/Calendar.app/"
    section: "apps"
    pos: 5
  - name: "System Preferences"
    path: "/System/Applications/System Preferences.app/"
    section: "apps"
    pos: 6
  - name: "Things3"
    path: "/Applications/Things3.app/"
    section: "apps"
    pos: 7
  - name: "Slack"
    path: "/Applications/Slack.app/"
    section: "apps"
    pos: 8
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    section: "apps"
    pos: 9
  - name: "Quiver"
    path: "/Applications/Quiver.app/"
    section: "apps"
    pos: 10
  - name: "Workplace Chat"
    path: "/Applications/Workplace Chat.app/"
    section: "apps"
    pos: 11
  - name: "OneDrive - Rentalcars.com"
    path: "/Users/ckr/OneDrive - Rentalcars.com/"
    section: "others"
    pos: 1
  - name: "Dropbox"
    path: "/Users/ckr/Dropbox/"
    section: "others"
    pos: 2
  - name: "Downloads"
    path: "/Users/ckr/Downloads/"
    section: "others"
    pos: 3
  - name: "Code of Conduct.webloc"
    path: "/Users/ckr/Library/Application Support/ConfigurationProfiles/Code of Conduct.webloc"
    section: "others"
    pos: 4
  - name: "BGO Compliance.webloc"
    path: "/Users/ckr/Library/Application Support/ConfigurationProfiles/BGO Compliance.webloc"
    section: "others"
    pos: 5

# MAS configuration
mas_enable: true
mas_signin_dialog: true
# Update all
mas_upgrade_all: true
# Make sure the following apps are installed/uninstalled
# Installed List
mas_installed:
  - { id: 866773894, name: "Quiver" }
  - { id: 1491071483, name: "Tot" }
  - { id: 904280696, name: "Things" }
  - { id: 1516894961, name: "Codye" }
  - { id: 587769990, name: "EyeFriendly" }
  - { id: 638161122, name: "YubiKey Personalization Tool" }
  - { id: 426410278, name: "Flexiglass" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 595191960, name: "CopyClip" }
  - { id: 568494494, name: "Pocket" }
  - { id: 1510445899, name: "Meeter" }
  - { id: 1354318707, name: "Core Tunnel" }

# Git configuration
git_enable: true

# Dotfiles configuration
dotfiles_enable: true

# Node packages via yarn
yarn_packages: []

# Node packages via npm
npm_packages: []

# Python packages via pip
pip_packages: []

# Ruby gems
gem_packages: []