# This playbook synchronizes SSH keys in
# ~/.ssh/authorized_keys with the public
# keys of the user's GitHub profile
---
- name: Fetching GitHub keys
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') | default(omit) }}"
    state: present
    key: "https://github.com/{{ github_ssh_keys_username }}.keys"
  when: github_ssh_keys_username is defined
