# This playbook synchronizes SSH keys in
# ~/.ssh/authorized_keys with the public
# keys of the user's GitHub profile
---
- name: Get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host

- name: Fetching GitHub keys
  authorized_key:
    user: "{{ lookup('env', 'USER') | default(omit) }}"
    state: present
    key: "https://github.com/{{ github_ssh_keys_username }}.keys"
  when: github_ssh_keys_username is defined
