---
- name: Install dependencies like zplug
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - zplug
    - fzf
  tags:
    - zplug

- name: Check if fzf is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/fzf"
  register: stat_fzf
  tags:
    - zsh
    - fzf

- name: Configure fzf
  ansible.builtin.shell: $(brew --prefix)/opt/fzf/install --no-bash --no-fish --completion --no-update-rc --key-bindings
  when: stat_fzf.stat.exists
  tags:
    - zsh
    - fzf
