---
- name: Copy dotfiles
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item | basename }}"
  with_fileglob:
    - "./dotfiles/*"
  tags:
    - files
    - dotaliases

- name: Ensure bin/ folder exists
  file:
    path: "{{ ansible_user_dir }}/bin"
    state: directory
  tags:
    - folders

- name: Ensure ~/work folder exists
  file:
    path: "{{ ansible_user_dir }}/work"
    state: directory
  tags:
    - folders

- name: Ensure ~/code folder exists
  file:
    path: "{{ ansible_user_dir }}/code"
    state: directory
  tags:
    - folders

- name: Copy bin/ files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/bin/{{ item | basename }}"
    mode: ug+rwx,o+rx
  with_fileglob:
    - "./bin/*"
  tags:
    - files
    - binfile

- name: Copy dotfiles files with template
  template:
    src: path_exports.j2
    dest: "{{ ansible_user_dir }}/.path_exports"
  tags:
    - files
    - dotaliases
