---
mactweaks_system_enable: false
# List your defaults write settings here
# for example change dock autohide to true
mactweaks_system_defaults: []
# - { domain: com.apple.dock, key: autohide, type: int, value: 1 }
