---
- name: Install dependencies
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ composer_homebrew_dependencies }}"
  tags:
    - composer_dependencies

- name: Change default php version
  community.general.homebrew:
    name: "{{ composer_defaults_php_version }}"
    state: linked
  tags:
    - default_php

- name: Install global Composer packages.
  community.general.composer:
    command: "{{ (item.state | default('present') == 'absent') | ternary('remove', 'require') }}"
    arguments: "{{ item.name | default(item) }} {{ item.version | default('@stable') }}"
    global_command: yes
  loop: "{{ composer_packages }}"
  tags:
    - composer_packages
