---
- name: Ensure configured taps are tapped.
  community.general.homebrew_tap:
    tap: '{{ item.name | default(item) }}'
    url: '{{ item.url | default(omit) }}'
    state: present
  loop: "{{ homebrew_taps }}"

- name: Ensure configured homebrew packages are installed.
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ homebrew_packages_installed }}"
  tags:
    - homebrew_packages

- name: Ensure blacklisted homebrew packages are not installed.
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    state: absent
  loop: "{{ homebrew_packages_uninstalled }}"
  tags:
    - homebrew_packages

- name: Upgrade all homebrew packages (if configured).
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  when: homebrew_upgrade_all
  tags:
    - homebrew_packages


- name: Install configured cask applications.
  community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' + homebrew_casks_appdir) }}"
    accept_external_apps: "{{ homebrew_casks_accept_external }}"
  loop: "{{ homebrew_casks_installed }}"
  tags:
    - homebrew_packages

- name: Uninstall configured cask applications.
  community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: absent
  loop: "{{ homebrew_casks_uninstalled }}"
  tags:
    - homebrew_packages
