---
- name: Check the current Dock position of {{ item.name | default(item) }}
  ansible.builtin.command:
    cmd: dockutil --find '{{ item.name | default(item) }}'
  register: dockitem_position
  failed_when: '"command not found" in dockitem_position.stdout'
  changed_when: false
  tags:
    - dock

- name: Get current dock item position from output.
  ansible.builtin.set_fact:
    current_position: "{{ dockitem_position | regex_replace('^.*slot (.*) in.*$', '\\1') }}"
  tags:
    - dock

- name: Move dock item to the correct position.
  ansible.builtin.command:
    cmd: dockutil --move '{{ item.name | default(item) }}' --position '{{ item.pos }} --no-restart'
  register: dockitem_move
  changed_when: dockitem_move.rc != 0
  when: current_position|int != item.pos|int
  tags:
    - dock
