---
- name: Check Dock item exists {{ item.name | default(item) }}
  ansible.builtin.command: dockutil --find '{{ item.name }}'
  register: dockitem_exists
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  changed_when: false
  tags:
    - dock

- name: Ensure Dock item exists {{ item.name | default(item) }}
  ansible.builtin.command: dockutil --add '{{ item.path }}' --section {{ item.section }} --no-restart
  register: dockitem_add
  changed_when: dockitem_add.rc != 0
  when: dockitem_exists.rc >0
  tags:
    - dock
