---
- name: Check Dock item exists {{ item }}
  ansible.builtin.command:
    cmd: dockutil --find '{{ item }}'
  register: dockitem_exists
  changed_when: false
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  tags:
    - dock

- name: Ensure Dock item is removed {{ item }}
  ansible.builtin.command:
    cmd: dockutil --remove '{{ item }}' --no-restart
  register: dockitem_remove
  changed_when: dockitem_remove.rc != 0
  when: dockitem_exists.rc  == 0
  tags:
    - dock
