---
- name: Installing Zsh and git dependencies (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ zplug.dependenciesBrew }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages
    - terminal

- name: check if ~/.zshrc exists
  stat:
    path: "{{ ansible_user_dir}}/.zshrc"
  register: stat_zshrc
  tags:
    - files
    
- name: Backing up existing ~/.zshrc
  copy: src={{ ansible_user_dir }}/.zshrc dest={{ ansible_user_dir }}/.zshrc.orig
  when: stat_zshrc.stat.exists == True
  tags:
    - files

- name: Check if fzf is installed
  stat:
    path: "/usr/local/bin/fzf"
  register: stat_fzf
  tags:
    - terminal
    - fzf

- name: Configure fzf
  shell: $(brew --prefix)/opt/fzf/install --no-bash --no-fish --completion --no-update-rc --key-bindings
  when: stat_fzf.stat.exists == True
  tags:
    - terminal
    - fzf

- name: Chanching default shell to zsh
  shell: chsh -s $(grep /zsh$ /etc/shells | tail -1)
  when: ansible_facts.user_shell != '/bin/zsh'
  tags:
    - terminal

- name: Copy dotfiles
  copy: src={{ item }} dest={{ ansible_user_dir }}/.{{ item | basename }}
  with_fileglob:
    - ./dotfiles/*
  tags:
    - files
    - dotaliases
    - spaceship
